branches:
  - Branch: master
defaultTemplate: all
templates:
  - Template: all
    variants:
      - darwinintel64_ios
     #- darwinintel64_ios_beta
variants:
  - Variant: darwinintel64_ios
    runtime: darwinintel64_ios
  #- Variant: darwinintel64_ios_beta
  #  runtime: darwinintel64_ios_beta
attributes:
  NoEmailToTeam: true